# Code generated by lark_sdk_gen. DO NOT EDIT.

from pylark.log import logger
from tests.test_conf import app_all_permission
import unittest
import pylark
import pytest


class Test_MeetingRoom_Sample_RequestFailed(unittest.TestCase):
    def __init__(self):
        super().__init__()
        self.cli = app_all_permission.ins()
        # self.cli.mock().MockGetTenantAccessToken(mockGetTenantAccessTokenFailed)
        # self.cli.mock().MockGetAppAccessToken(mockGetTenantAccessTokenFailed)
        self.module_cli = self.cli.meeting_room

    def test_request_failed_batch_get_meeting_room_summary(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.BatchGetMeetingRoomSummary(
                pylark.BatchGetMeetingRoomSummaryReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_get_meeting_room_building_list(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.GetMeetingRoomBuildingList(
                pylark.GetMeetingRoomBuildingListReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_batch_get_meeting_room_building(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.BatchGetMeetingRoomBuilding(
                pylark.BatchGetMeetingRoomBuildingReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_get_meeting_room_room_list(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.GetMeetingRoomRoomList(
                pylark.GetMeetingRoomRoomListReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_batch_get_meeting_room_room(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.BatchGetMeetingRoomRoom(
                pylark.BatchGetMeetingRoomRoomReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_batch_get_meeting_room_freebusy(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.BatchGetMeetingRoomFreebusy(
                pylark.BatchGetMeetingRoomFreebusyReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_reply_meeting_room_instance(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.ReplyMeetingRoomInstance(
                pylark.ReplyMeetingRoomInstanceReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_create_meeting_room_building(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.CreateMeetingRoomBuilding(
                pylark.CreateMeetingRoomBuildingReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_update_meeting_room_building(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.UpdateMeetingRoomBuilding(
                pylark.UpdateMeetingRoomBuildingReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_delete_meeting_room_building(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.DeleteMeetingRoomBuilding(
                pylark.DeleteMeetingRoomBuildingReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_batch_get_meeting_room_building_id(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.BatchGetMeetingRoomBuildingID(
                pylark.BatchGetMeetingRoomBuildingIDReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_create_meeting_room_room(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.CreateMeetingRoomRoom(
                pylark.CreateMeetingRoomRoomReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_update_meeting_room_room(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.UpdateMeetingRoomRoom(
                pylark.UpdateMeetingRoomRoomReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_delete_meeting_room_room(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.DeleteMeetingRoomRoom(
                pylark.DeleteMeetingRoomRoomReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_batch_get_meeting_room_room_id(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.BatchGetMeetingRoomRoomID(
                pylark.BatchGetMeetingRoomRoomIDReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_get_meeting_room_country_list(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.GetMeetingRoomCountryList(
                pylark.GetMeetingRoomCountryListReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")

    def test_request_failed_get_meeting_room_district_list(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.GetMeetingRoomDistrictList(
                pylark.GetMeetingRoomDistrictListReq()
            )
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")
