# Code generated by lark_sdk_gen. DO NOT EDIT.

from tests.test_conf import app_all_permission
import unittest
import pylark
import pytest
from tests.test_helper import mock_get_tenant_access_token_failed


class TestEHRSampleRequestFailed(unittest.TestCase):
    def __init__(self, *args, **kwargs):
        super(TestEHRSampleRequestFailed, self).__init__(*args, **kwargs)
        self.cli = app_all_permission.ins()
        self.cli.auth.get_tenant_access_token = mock_get_tenant_access_token_failed
        self.cli.auth.get_app_access_token = mock_get_tenant_access_token_failed
        self.module_cli = self.cli.ehr

    def test_request_failed_get_ehr_employee_list(self):
        with pytest.raises(pylark.PyLarkError) as e:
            self.module_cli.get_ehr_employee_list(pylark.GetEHREmployeeListReq())

        assert "msg=failed" in f"{e}"

    def test_request_failed_download_ehr_attachments(self):
        with pytest.raises(pylark.PyLarkError) as e:
            self.module_cli.download_ehr_attachments(pylark.DownloadEHRAttachmentsReq())

        assert "msg=failed" in f"{e}"
