# Code generated by lark_sdk_gen. DO NOT EDIT.

from tests.test_conf import app_all_permission
import unittest
import pylark
import pytest
from tests.test_helper import mock_get_tenant_access_token_failed


class TestFileSampleRequestFailed(unittest.TestCase):
    def __init__(self, *args, **kwargs):
        super(TestFileSampleRequestFailed, self).__init__(*args, **kwargs)
        self.cli = app_all_permission.ins()
        self.cli.auth.get_tenant_access_token = mock_get_tenant_access_token_failed
        self.cli.auth.get_app_access_token = mock_get_tenant_access_token_failed
        self.module_cli = self.cli.file

    def test_request_failed_upload_image(self):
        with pytest.raises(pylark.PyLarkError) as e:
            self.module_cli.upload_image(pylark.UploadImageReq())

        assert "msg=failed" in f"{e}"

    def test_request_failed_download_image(self):
        with pytest.raises(pylark.PyLarkError) as e:
            self.module_cli.download_image(pylark.DownloadImageReq())

        assert "msg=failed" in f"{e}"

    def test_request_failed_upload_file(self):
        with pytest.raises(pylark.PyLarkError) as e:
            self.module_cli.upload_file(pylark.UploadFileReq())

        assert "msg=failed" in f"{e}"

    def test_request_failed_download_file(self):
        with pytest.raises(pylark.PyLarkError) as e:
            self.module_cli.download_file(pylark.DownloadFileReq())

        assert "msg=failed" in f"{e}"
