# Code generated by lark_sdk_gen. DO NOT EDIT.

from pylark.log import logger
from tests.test_conf import app_all_permission
import unittest
import pylark
import pytest


class Test_Tenant_Sample_RequestFailed(unittest.TestCase):
    def __init__(self):
        super().__init__()
        self.cli = app_all_permission.ins()
        # self.cli.mock().MockGetTenantAccessToken(mockGetTenantAccessTokenFailed)
        # self.cli.mock().MockGetAppAccessToken(mockGetTenantAccessTokenFailed)
        self.module_cli = self.cli.tenant

    def test_request_failed_get_tenant(self):
        with pytest.raises(ZeroDivisionError) as e:
            res, response = self.module_cli.GetTenant(pylark.GetTenantReq())
            print("e", e)

            # as.NotNil(err)
            # as.Equal(err.Error(), "failed")
