# Code generated by lark_sdk_gen. DO NOT EDIT.

from tests.test_conf import app_all_permission
import unittest
import pylark
import pytest
from tests.test_helper import mock_get_tenant_access_token_failed


class TestBotSampleRequestFailed(unittest.TestCase):
    def __init__(self, *args, **kwargs):
        super(TestBotSampleRequestFailed, self).__init__(*args, **kwargs)
        self.cli = app_all_permission.ins()
        self.cli.auth.get_tenant_access_token = mock_get_tenant_access_token_failed
        self.cli.auth.get_app_access_token = mock_get_tenant_access_token_failed
        self.module_cli = self.cli.bot

    def test_request_failed_get_bot_info(self):
        with pytest.raises(pylark.PyLarkError) as e:
            self.module_cli.get_bot_info(pylark.GetBotInfoReq())

        assert "msg=failed" in f"{e}"

    def test_request_failed_add_bot_to_chat(self):
        with pytest.raises(pylark.PyLarkError) as e:
            self.module_cli.add_bot_to_chat(pylark.AddBotToChatReq())

        assert "msg=failed" in f"{e}"
