# Code generated by lark_sdk_gen. DO NOT EDIT.

from pylark.lark_request import RawRequestReq, _new_method_option
from pylark import lark_type, lark_type_sheet, lark_type_approval
import attr
import typing
import io


@attr.s
class OpenBotReq(object):
    app_id: str = attr.ib(
        default="", metadata={"req_type": "json", "key": "appId"}
    )  # 机器人的appId


@attr.s
class OpenBotResp(object):
    pass


def _gen_open_bot_req(request, options) -> RawRequestReq:
    return RawRequestReq(
        dataclass=OpenBotResp,
        scope="AppLink",
        api="OpenBot",
        method="",
        url="https://applink.feishu.cn/client/bot/open",
        body=request,
        method_option=_new_method_option(options),
    )
