# Code generated by lark_sdk_gen. DO NOT EDIT.

from pylark.lark_request import RawRequestReq, _new_method_option
import attr
import typing
import io


@attr.s
class UpdateContactGroupReq(object):
    group_id: str = attr.ib(
        default="", metadata={"req_type": "path"}
    )  # 用户组ID, 示例值："g187131"
    name: str = attr.ib(
        default="", metadata={"req_type": "json"}
    )  # 用户组的名字，企业内唯一，最大长度：100 字符, 示例值："外包 IT 用户组"
    description: str = attr.ib(
        default="", metadata={"req_type": "json"}
    )  # 用户组描述信息,最大长度：500 字, 示例值："IT 外包用户组，需要进行细粒度权限管控"


@attr.s
class UpdateContactGroupResp(object):
    pass


def _gen_update_contact_group_req(request, options) -> RawRequestReq:
    return RawRequestReq(
        dataclass=UpdateContactGroupResp,
        scope="Contact",
        api="UpdateContactGroup",
        method="PATCH",
        url="https://open.feishu.cn/open-apis/contact/v3/group/:group_id",
        body=request,
        method_option=_new_method_option(options),
        need_tenant_access_token=True,
    )
