# Code generated by lark_sdk_gen. DO NOT EDIT.

from pylark.lark_request import RawRequestReq, _new_method_option
from pylark import lark_type, lark_type_sheet, lark_type_approval
import attr
import typing
import io


@attr.s
class GetMessageReq(object):
    message_id: str = attr.ib(
        default="", metadata={"req_type": "path", "key": "message_id"}
    )  # 待获取消息内容的消息的ID, 示例值："om_dc13264520392913993dd051dba21dcf"


@attr.s
class GetMessageRespItem(object):
    message_id: str = attr.ib(
        default="", metadata={"req_type": "json", "key": "message_id"}
    )  # 消息id，说明参见：[消息ID说明](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/intro#ac79c1c2)
    root_id: str = attr.ib(
        default="", metadata={"req_type": "json", "key": "root_id"}
    )  # 根消息id，说明参见：[消息ID说明](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/intro#ac79c1c2)
    parent_id: str = attr.ib(
        default="", metadata={"req_type": "json", "key": "parent_id"}
    )  # 父消息的id，说明参见：[消息ID说明](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/intro#ac79c1c2)
    msg_type: lark_type.MsgType = attr.ib(
        factory=lambda: lark_type.MsgType(),
        metadata={"req_type": "json", "key": "msg_type"},
    )  # 消息类型 包括：text、post、image、file、audio、media、sticker、interactive、share_chat、share_user等，类型定义请参考[发送消息content说明](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/im-v1/message/create_json)
    create_time: str = attr.ib(
        default="", metadata={"req_type": "json", "key": "create_time"}
    )  # 消息生成的时间戳（毫秒）
    update_time: str = attr.ib(
        default="", metadata={"req_type": "json", "key": "update_time"}
    )  # 消息更新的时间戳（毫秒）
    deleted: bool = attr.ib(
        factory=lambda: bool(), metadata={"req_type": "json", "key": "deleted"}
    )  # 消息是否被撤回
    updated: bool = attr.ib(
        factory=lambda: bool(), metadata={"req_type": "json", "key": "updated"}
    )  # 消息是否被更新
    chat_id: str = attr.ib(
        default="", metadata={"req_type": "json", "key": "chat_id"}
    )  # 所属的群
    sender: lark_type.Sender = attr.ib(
        default=None, metadata={"req_type": "json", "key": "sender"}
    )  # 发送者，可以是用户或应用
    body: lark_type.MessageBody = attr.ib(
        default=None, metadata={"req_type": "json", "key": "body"}
    )  # 消息内容
    mentions: typing.List[lark_type.Mention] = attr.ib(
        factory=lambda: [], metadata={"req_type": "json", "key": "mentions"}
    )  # 被@的用户或机器人的id列表
    upper_message_id: str = attr.ib(
        default="", metadata={"req_type": "json", "key": "upper_message_id"}
    )  # 合并转发消息中，上一层级的消息id message_id，说明参见：[消息ID说明](https://open.feishu.cn/document/uAjLw4CM/ukTMukTMukTM/reference/im-v1/message/intro#ac79c1c2)


@attr.s
class GetMessageResp(object):
    items: typing.List[GetMessageRespItem] = attr.ib(
        factory=lambda: [], metadata={"req_type": "json", "key": "items"}
    )  # -


def _gen_get_message_req(request, options) -> RawRequestReq:
    return RawRequestReq(
        dataclass=GetMessageResp,
        scope="Message",
        api="GetMessage",
        method="GET",
        url="https://open.feishu.cn/open-apis/im/v1/messages/:message_id",
        body=request,
        method_option=_new_method_option(options),
        need_tenant_access_token=True,
    )
