# Code generated by lark_sdk_gen. DO NOT EDIT.

from pylark.lark_request import RawRequestReq, _new_method_option
import attr
import typing
import io


@attr.s
class BatchDeleteMessageReq(object):
    batch_message_id: str = attr.ib(
        default="", metadata={"req_type": "path"}
    )  # 待撤回的批量消息的ID, 示例值："bm-dc13264520392913993dd051dba21dcf"


@attr.s
class BatchDeleteMessageResp(object):
    pass


def _gen_batch_delete_message_req(request, options) -> RawRequestReq:
    return RawRequestReq(
        dataclass=BatchDeleteMessageResp,
        scope="Message",
        api="BatchDeleteMessage",
        method="DELETE",
        url="https://open.feishu.cn/open-apis/im/v1/batch_messages/:batch_message_id",
        body=request,
        method_option=_new_method_option(options),
        need_tenant_access_token=True,
    )
