# Code generated by lark_sdk_gen. DO NOT EDIT.

from pylark.lark_request import RawRequestReq, _new_method_option
import attr
import typing
import io


@attr.s
class DeleteHelpdeskCategoryReq(object):
    id: str = attr.ib(
        default="", metadata={"req_type": "path"}
    )  # 知识库分类ID, 示例值："6948728206392295444"


@attr.s
class DeleteHelpdeskCategoryResp(object):
    pass


def _gen_delete_helpdesk_category_req(request, options) -> RawRequestReq:
    return RawRequestReq(
        dataclass=DeleteHelpdeskCategoryResp,
        scope="Helpdesk",
        api="DeleteHelpdeskCategory",
        method="DELETE",
        url="https://open.feishu.cn/open-apis/helpdesk/v1/categories/:id",
        body=request,
        method_option=_new_method_option(options),
        need_user_access_token=True,
        need_helpdesk_auth=True,
    )
