# Code generated by lark_sdk_gen. DO NOT EDIT.

from pylark.lark_request import RawRequestReq, _new_method_option
from pylark import lark_type, lark_type_sheet, lark_type_approval
import attr
import typing
import io


@attr.s
class CreateContactUnitReq(object):
    unit_id: str = attr.ib(
        default="", metadata={"req_type": "json", "key": "unit_id"}
    )  # 单位自定义ID。不带默认自动生成。1-64字节范围大小，需为数字字母, 示例值："BU121"
    name: str = attr.ib(
        default="", metadata={"req_type": "json", "key": "name"}
    )  # 单位的名字，长度范围为1-100个字, 示例值："消费者事业部"
    unit_type: str = attr.ib(
        default="", metadata={"req_type": "json", "key": "unit_type"}
    )  # 单位类型，长度范围为1-100个字，创建后不可修改, 示例值："事业部"


@attr.s
class CreateContactUnitResp(object):
    unit_id: str = attr.ib(
        default="", metadata={"req_type": "json", "key": "unit_id"}
    )  # 单位的自定义ID


def _gen_create_contact_unit_req(request, options) -> RawRequestReq:
    return RawRequestReq(
        dataclass=CreateContactUnitResp,
        scope="Contact",
        api="CreateContactUnit",
        method="POST",
        url="https://open.feishu.cn/open-apis/contact/v3/unit",
        body=request,
        method_option=_new_method_option(options),
        need_tenant_access_token=True,
    )
