# Code generated by lark_sdk_gen. DO NOT EDIT.

from pylark.lark_request import RawRequestReq, _new_method_option
from pylark import lark_type, lark_type_sheet, lark_type_approval
import attr
import typing
import io


@attr.s
class UpdateDriveCommentPatchReq(object):
    file_type: lark_type.FileType = attr.ib(
        factory=lambda: lark_type.FileType(),
        metadata={"req_type": "query", "key": "file_type"},
    )  # 文档类型, 示例值："doc", 可选值有: `doc`：文档, `sheet`：表格, `file`：文件
    file_token: str = attr.ib(
        default="", metadata={"req_type": "path", "key": "file_token"}
    )  # 文档token, 示例值："doccnGp4UK1UskrOEJwBXd3****"
    comment_id: str = attr.ib(
        default="", metadata={"req_type": "path", "key": "comment_id"}
    )  # 评论ID, 示例值："6916106822734578184"
    is_solved: bool = attr.ib(
        factory=lambda: bool(), metadata={"req_type": "json", "key": "is_solved"}
    )  # 评论解决标志, 示例值：true


@attr.s
class UpdateDriveCommentPatchResp(object):
    pass


def _gen_update_drive_comment_patch_req(request, options) -> RawRequestReq:
    return RawRequestReq(
        dataclass=UpdateDriveCommentPatchResp,
        scope="Drive",
        api="UpdateDriveCommentPatch",
        method="PATCH",
        url="https://open.feishu.cn/open-apis/drive/v1/files/:file_token/comments/:comment_id",
        body=request,
        method_option=_new_method_option(options),
        need_tenant_access_token=True,
        need_user_access_token=True,
    )
